/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { VersaTokenConsumerUniV2__factory } from "./VersaTokenConsumerUniV2__factory";
export { VersaTokenConsumerUniV2Errors__factory } from "./VersaTokenConsumerUniV2Errors__factory";
