/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  VersaTokenConsumerUniV2Errors,
  VersaTokenConsumerUniV2ErrorsInterface,
} from "../../../contracts/VersaTokenConsumerUniV2.strategy.sol/VersaTokenConsumerUniV2Errors";

const _abi = [
  {
    inputs: [],
    name: "InputCantBeZero",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidAddress",
    type: "error",
  },
];

export class VersaTokenConsumerUniV2Errors__factory {
  static readonly abi = _abi;
  static createInterface(): VersaTokenConsumerUniV2ErrorsInterface {
    return new utils.Interface(_abi) as VersaTokenConsumerUniV2ErrorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VersaTokenConsumerUniV2Errors {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as VersaTokenConsumerUniV2Errors;
  }
}
