/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as immutableCreate2FactorySol from "./ImmutableCreate2Factory.sol";
export type { immutableCreate2FactorySol };
import type * as versaEthSol from "./Versa.eth.sol";
export type { versaEthSol };
import type * as versaNonEthSol from "./Versa.non-eth.sol";
export type { versaNonEthSol };
import type * as versaConnectorBaseSol from "./VersaConnector.base.sol";
export type { versaConnectorBaseSol };
import type * as versaConnectorEthSol from "./VersaConnector.eth.sol";
export type { versaConnectorEthSol };
import type * as versaConnectorNonEthSol from "./VersaConnector.non-eth.sol";
export type { versaConnectorNonEthSol };
import type * as versaTokenConsumerUniV2StrategySol from "./VersaTokenConsumerUniV2.strategy.sol";
export type { versaTokenConsumerUniV2StrategySol };
import type * as versaTokenConsumerUniV3StrategySol from "./VersaTokenConsumerUniV3.strategy.sol";
export type { versaTokenConsumerUniV3StrategySol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as openzeppelin from "./openzeppelin";
export type { openzeppelin };
import type * as testing from "./testing";
export type { testing };
export type { versaInteractor } from "./versaInteractor";
