/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  VersaTokenConsumerUniV3Errors,
  VersaTokenConsumerUniV3ErrorsInterface,
} from "../../../contracts/VersaTokenConsumerUniV3.strategy.sol/VersaTokenConsumerUniV3Errors";

const _abi = [
  {
    inputs: [],
    name: "ErrorSendingETH",
    type: "error",
  },
  {
    inputs: [],
    name: "InputCantBeZero",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "ReentrancyError",
    type: "error",
  },
];

export class VersaTokenConsumerUniV3Errors__factory {
  static readonly abi = _abi;
  static createInterface(): VersaTokenConsumerUniV3ErrorsInterface {
    return new utils.Interface(_abi) as VersaTokenConsumerUniV3ErrorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VersaTokenConsumerUniV3Errors {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as VersaTokenConsumerUniV3Errors;
  }
}
