/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VersaTokenConsumerUniV2 } from "./VersaTokenConsumerUniV2";
export type { VersaTokenConsumerUniV2Errors } from "./VersaTokenConsumerUniV2Errors";
