/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as VersaInterfacesSol from "./VersaInterfaces.sol";
export type { VersaInterfacesSol };
export type { ConnectorErrors } from "./ConnectorErrors";
export type { VersaErrors } from "./VersaErrors";
export type { VersaInteractorErrors } from "./VersaInteractorErrors";
export type { VersaNonEthInterface } from "./VersaNonEthInterface";
