/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VersaConnector } from "./VersaConnector";
export type { VersaReceiver } from "./VersaReceiver";
export type { VersaTokenConsumer } from "./VersaTokenConsumer";
