/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  VersaReceiver,
  VersaReceiverInterface,
} from "../../../../contracts/interfaces/VersaInterfaces.sol/VersaReceiver";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "VersaTxSenderAddress",
            type: "bytes",
          },
          {
            internalType: "uint256",
            name: "sourceChainId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "destinationAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "VersaValue",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "message",
            type: "bytes",
          },
        ],
        internalType: "struct VersaInterfaces.VersaMessage",
        name: "VersaMessage",
        type: "tuple",
      },
    ],
    name: "onVersaMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "VersaTxSenderAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "sourceChainId",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "destinationAddress",
            type: "bytes",
          },
          {
            internalType: "uint256",
            name: "destinationChainId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "remainingVersaValue",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "message",
            type: "bytes",
          },
        ],
        internalType: "struct VersaInterfaces.VersaRevert",
        name: "VersaRevert",
        type: "tuple",
      },
    ],
    name: "onVersaRevert",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class VersaReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): VersaReceiverInterface {
    return new utils.Interface(_abi) as VersaReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VersaReceiver {
    return new Contract(address, _abi, signerOrProvider) as VersaReceiver;
  }
}
