/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  VersaConnector,
  VersaConnectorInterface,
} from "../../../../contracts/interfaces/VersaInterfaces.sol/VersaConnector";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "destinationChainId",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "destinationAddress",
            type: "bytes",
          },
          {
            internalType: "uint256",
            name: "destinationGasLimit",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "message",
            type: "bytes",
          },
          {
            internalType: "uint256",
            name: "VersaValueAndGas",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "VersaParams",
            type: "bytes",
          },
        ],
        internalType: "struct VersaInterfaces.SendInput",
        name: "input",
        type: "tuple",
      },
    ],
    name: "send",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class VersaConnector__factory {
  static readonly abi = _abi;
  static createInterface(): VersaConnectorInterface {
    return new utils.Interface(_abi) as VersaConnectorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VersaConnector {
    return new Contract(address, _abi, signerOrProvider) as VersaConnector;
  }
}
