/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WETH9 } from "./WETH9";
export type { VersaTokenConsumerUniV3 } from "./VersaTokenConsumerUniV3";
export type { VersaTokenConsumerUniV3Errors } from "./VersaTokenConsumerUniV3Errors";
